#### Create a new User
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "dele1234567@test.com",
  "password": "hello world"
}


### sign in a particular user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "dele1234567@test.com",
  "password": "hello world"
}


### get the currently signed in user

GET http://localhost:3000/auth/user/me


###  sign out user

POST http://localhost:3000/auth/signout


### find a particular user with a given id
GET http://localhost:3000/auth/2


### find all users with a given email

GET http://localhost:3000/auth?email=dele@test.com

#### delete user with a given id
DELETE  http://localhost:3000/auth/3


#### Update a user

PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
  "email": "oladele101@test.com"
}


#### set a color

GET http://localhost:3000/auth/colors/red


#### Get color

GET http://localhost:3000/auth/colors
